config/routes.rb
Vaktliste::Application.routes.draw do
  resources :availability_statuses

  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"
  resources :seasons do
    resources :workdays
  end
  resources :user_sessions

  match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
  match 'logout' => 'user_sessions#destroy', :as => :logout,  via: [:get, :post]

  root "users#index"
  get "vakter" => "users#index", as: "vakter"
  post "vakter" => "users#create", as: "opprett_vakt"
  get "vakter/ny" => "users#new", as: "ny_vakt"
  get "vakter/:id" => "users#show", as: "vakt"
  get "vakter/:id/rediger" => "users#edit", as: "rediger_vakt"

  get "user/:id" => "users#show", as: "user"
  get "users/new" => "users#new", as: "users"
  patch "user/:id" => "users#update"

  post "workdays/:id" => "workdays#update"
  patch "workdays/:id" => "workdays#update"
  post "availability_statuses/:id" => "availability_statuses#ajax_update"

end

app/models/availability_status.rb
class AvailabilityStatus < ActiveRecord::Base
  belongs_to :user
  belongs_to :workday

  STATUS = { available: 0, unavailable: 1, undecided: 2 }

  def available
    status = STATUS.key(read_attribute(:available))
    if status == :available
      "Tilgjengeleg"
    elsif status == :unavailable
      "Ikkje tilgjengeleg"
    else
      "Veit ikkje"
    end
  end

  def available=(s)
    write_attribute(:available, STATUS[s])
  end

  def on_wishlist_checked
    empty = " "
    if on_wishlist
      "checked=\"checked\""
    else
      empty
    end
  end


  def selected_availability(selected)
    empty = " "
    status = STATUS.key(read_attribute(:available))
    if status == selected.to_sym
      return "checked=\"checked\""
    end
    return empty
  end

  def to_s
    "user_id: #{user_id}, workday_id: #{workday_id}, on_wishlist: #{on_wishlist}"
  end
end

app/models/season.rb
require 'date'
require 'chronic'
class Season < ActiveRecord::Base
  has_many :workdays

  def current_week_work_dates
    days = Array.new
    open_days.split(',').each do |day_num|
      days.append Date::DAYNAMES[day_num.to_i]
    end

    Chronic.parse("")
    work_dates = Array.new
    days.each do |day_name|
      work_dates.append Chronic.parse(" #{day_name}" )
    end
    work_dates.to_s
  end

  def number_of_open_weeks
    to_date.cweek - from_date.cweek
  end

  def open_weeks
    weeks = Hash.new
    week = from_date.cweek

    for i in 0..number_of_open_weeks
      cur_week = week + i
      weeks[cur_week] = work_dates_for_week(cur_week)
    end
    weeks
  end

  def open_weeks_with_days
    weeks = Hash.new
    week = from_date.cweek

    for i in 0..number_of_open_weeks
      cur_week = week + i
      weeks[cur_week] = Array.new
    end

    workdays.each do |day|
      weeks[day.date.cweek].append(day)
    end

    weeks
  end

  def work_dates_for_week(week_number)

    monday = Date.commercial(2013, week_number, 1)
    day_numbers = Array.new
    open_days.split(',').each do |day_num|
      day_numbers.append((day_num.to_i - 1))
    end

    work_dates = Array.new
    day_numbers.each do |d|
      work_dates.append(monday + d)
    end

    return work_dates
  end

  def init_workdays_for_season
    weeks = open_weeks()
    weeks.each do |k,v|
      v.each do |day|
        workday = Workday.new
        workday.date = day
        workday.season_id = id
        workday.save
      end

    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :workdays
  has_many :availability_statuses
  validates_length_of :password, :minimum => 3, :message => "password must be at least 3 characters long", :if => :password
  def is_admin?
    admin
  end
end

app/models/workday.rb
class Workday < ActiveRecord::Base
  belongs_to :person_1, :class_name => 'User'
  belongs_to :person_2, :class_name => 'User'
  belongs_to :season
  has_many :availability_statuses

  def status_level
    if person_1.nil? && person_2.nil?
      "not_staffed"
    elsif (!person_1.nil? && person_2.nil?) || (person_1.nil? && !person_2.nil?)
      "partially_staffed"
    else
      "staffed"
    end
  end

  def availability_status_for(user_id)
    status = AvailabilityStatus.where("user_id = ? and workday_id = ?", user_id, id).first
    if status.nil?
      puts "status is nil"
      status = AvailabilityStatus.new
      status.user_id = user_id
      status.workday_id = id
      status.on_wishlist = false
      status.save
    end
    return status
  end

  def availability_info
    # availability_statuses.to_a
    AvailabilityStatus.where("workday_id = ?",  id).to_a
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  protected
  def not_authenticated
    redirect_to login_path, :alert => "Vennligst logg inn f&oslash;rst."
  end
end

app/controllers/availability_statuses_controller.rb
class AvailabilityStatusesController < ApplicationController

  def index
    @season = Season.last
    @season.open_weeks_with_days.each do |k, v|
      v.each do |day|
        status = AvailabilityStatus.where("user_id = ? and workday_id = ?", @current_user.id, day.id).first
        if status.nil?
          status = AvailabilityStatus.new
          status.user_id = @current_user.id
          status.workday_id = day.id
          status.on_wishlist = false
          status.save
        end
      end
    end
  end

  def ajax_update
    @status = AvailabilityStatus.find(params[:id])
    @field = params[:user_input][:field]
    value = params[:user_input][:value]
    if @field == "available"
      @status.available=value.to_sym
      puts "available set to #{value}"
    elsif @field == "on_wishlist"
      @status.on_wishlist=value
      puts "on_wishlist set to #{value}"
    end
    @status.save
    puts "Availability status saved: #{status.to_s}"

    respond_to do |format|
      format.js
    end
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @season = Season.last
    @users = User.all.sort
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

# app/controllers/user_sessions_controller.rb
  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(params[:username],params[:password])
        format.html { redirect_back_or_to(:seasons, :notice => 'Du er logga inn.') }
        format.xml { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { flash.now[:alert] = "Beklager, feil brukarnamn eller passord."; render :action => "new" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(:login, :notice => 'Du er no logga ut.')
  end
end

app/controllers/users_controller.rb
require_relative "../models/user"

class UsersController < ApplicationController
  # app/controllers/users_controller.rb
  # skip_before_filter :require_login, :only => [:index]

  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @workdays = Workday.where(["person_1_id = ? or person_2_id = ?", @user.id, @user.id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :password, :admin, :comments, :phone, :email, :started_date, :quit_date, :active)
  end

end

app/controllers/workdays_controller.rb
class WorkdaysController < ApplicationController
  def update
    @day = Workday.find(params[:id])
    field = params[:person][:field]
    value = params[:person][:value]

    if !value.nil?
      eval("@day.#{field}=#{value}")
      @day.save

      @person_1 = User.find(@day.person_1_id) unless @day.person_1_id.nil?
      @person_2 = User.find(@day.person_2_id) unless @day.person_2_id.nil?

    end

    respond_to do |format|
      format.js
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availability_statuses_helper.rb
module AvailabilityStatusesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workdays_helper.rb
module WorkdaysHelper
end

app/views/availability_statuses/ajax_update.js.erb
$("#status_form_<%=@status.id%>").effect("highlight", {color:'#ffff99'});

app/views/availability_statuses/index.html.erb
<h1 xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <%= @season.name %>, frå <%= I18n.localize @season.from_date %> til <%= I18n.localize @season.to_date %> </h1>
<p>Fint om du kan krysse av for kva dagar du er tilgjengeleg og kva dagar du eventuelt ønskjer spesielt å jobbe.
  Dette vil vere eit nyttig verktøy ved byte av vakter, sjukdom etc.</p>
<p>Alle avkrysningar vert lagra automatisk. Eit lite gult blink viser at valet har vorte lagra.</p>
<table class="table table-striped table-condensed seasons-table" border="1">

  <% @season.open_weeks_with_days.each do |k, v| %>
      <tr>
        <th align="left" colspan="<%= v.length %>"> Veke: <%= k %>:</th>
      </tr>
      <tr>
      <% v.each do |day| %>
      <% status = day.availability_status_for(current_user.id) %>
            <td><b><%= I18n.localize day.date, :format => :long %></b>
              <form method="post" id="<%= "status_form_#{status.id}" %>" action="" role="form" class="form-horizontal">
                <input type="hidden" value="<%= status.id %>" id="available_status_id_<%= status.id %>" class="status_field"/>
                <label for="available_<%=status.id%>">
                  <input id="available_<%=status.id%>" type="radio" value="<%="available"%>"
                         onclick="post_available(<%=status.id%>, this);"
                         name="available" <%= status.selected_availability("available") %> />
                  Er tilgjengeleg
                </label>
                <label for="unavailable_<%=status.id%>">
                  <input id="unavailable_<%=status.id%>" type="radio" value="<%="unavailable"%>"
                         onclick="post_available(<%=status.id%>, this);"
                         name="available" <%= status.selected_availability("unavailable") %> />
                  Ikkje tilgjengeleg
                </label>
                <label for="undecided_<%=status.id%>">
                  <input id="undecided_<%=status.id%>" type="radio" value="<%="undecided"%>"
                         onclick="post_available(<%=status.id%>, this);"
                         name="available" <%= status.selected_availability("undecided") %>  />
                  Veit ikkje
                </label>
                <div class="checkbox">
                  <label for="on_wishlist_id_<%=status.id%>">
                    <input name="on_wishlist" type="hidden" value="0" />
                    <input id="on_wishlist_id_<%=status.id%>" type="checkbox" name="on_wishlist"
                           onclick="post_on_wishlist(<%=status.id%>, this);"
                           value="1" <%= status.on_wishlist_checked %> />
                    Ønsker å jobbe denne dagen
                  </label>
                </div>
              </form>
            </td>
      <% end %>
      </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Vaktliste" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/seasons">Vaktplan</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Badevakter", "/vakter"  %></li>
              <li><%= link_to "Registrer ny bruker", "/vakter/ny"  %></li>
              <li><%= link_to "Min tilgjengelighet", "/availability_statuses"  %></li>
              <% if current_user %>
                  <li> <%= link_to "Logga inn som: #{current_user.name}", "/vakter/#{current_user.id}" %></li>
                  <li> <%= link_to "Logg ut", :logout %></li>
            <% else %>
                 <li> <%= link_to "Login", :login %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row" id="real_content">
          <div class="span9" >
            <%= bootstrap_flash %>
            <%= yield %>
          </div>

        </div><!--/row-->

      <footer>
        <p>&copy; Hanna Ahlström & Ørjan Taule 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/seasons/index.html.erb
<h1 xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <%= @season.name %>, frå <%= I18n.localize @season.from_date %> til <%= I18n.localize @season.to_date %> </h1>

<table class="table seasons-table">
  <thead>
  <tr>
    <th colspan="3">Fargeforklaring</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td class="not_staffed">Ingen oppsatte vakter</td>
    <td class="partially_staffed">Berre ein vakt</td>
    <td class="staffed">Fullt oppsatt</td>
  </tr>
  </tbody>
</table>

<div class="table-responsive">
<table class="table table-striped seasons-table">
  <% @season.open_weeks_with_days.each do |k, v| %>
      <tr>
        <th align="left" colspan="<%= v.length %>"> Veke: <%= k %>:</th>
      </tr>
      <tr>
        <% v.each do |day| %>
            <td><%= I18n.localize day.date, :format => :long %></td>
        <% end %>
      </tr>
      <tr>
        <% v.each do |day| %>
            <td id="info_day_<%= day.id %>" class="<%= day.status_level %>">
              <span id="person_1_day_<%= day.id %>" class="person_1">Vakt 1: <%= day.person_1.nil? ? "ingen" : day.person_1.name %> </span>
              <br/>
              <span id="person_2_day_<%= day.id %>" class="person_2">Vakt 2: <%= day.person_2.nil? ? "ingen" : day.person_2.name %> </span>
            </td>
        <% end %>
      </tr>
      <tr>
        <% v.each do |day| %>
            <td>
              <a href="javascript:void();" onclick="$('#tilgjengelige_vakter_<%=day.id%>').toggle(100);">
                <b>Info om tilgjengelege vakter </b><i class="icon-expand-alt"></i></a>
              <ul id="tilgjengelige_vakter_<%= day.id %>" class="tilgjengelege_vakter_liste list-unstyled">
                <% day.availability_info.each do |a| %>
                    <li><b><%= "#{a.user.name}"%></b> <%= "(#{a.user.phone}):" %><br/><%= a.available %>
                      <% if a.on_wishlist %>
                          <i style="cursor: pointer;" title="Ønsker spesielt å jobbe denne dagen." class="icon-heart"></i>
                      <% end %></li>
                <% end %>
              </ul>
        <% end %>
        </td>
      </tr>
      <% if current_user && current_user.is_admin? %>
          <tr>
            <% v.each do |day| %>
                <td>

                  <%= form_for(day, url: opprett_vakt_path, method: "patch") do |f| %>
                      <input type="hidden" value="<%= day.id %>" id="day_<%= day.id %>" class="day_field"/>
                      <select id="day_<%= day.id %>_person_1" name="person_1_id">
                        <option>Velg vakt 1</option>
                        <%= options_from_collection_for_select(@users, :id, :name) %>
                        <option value="nil">Ingen</option>
                      </select>
                      <select id="day_<%= day.id %>_person_2" name="person_2_id">
                        <option>Velg vakt 2</option>
                        <%= options_from_collection_for_select(@users, :id, :name) %>
                        <option value="nil">Ingen</option>
                      </select>
                  <% end %>
                </td>
            <% end %>
          </tr>
      <% end %>
  <% end %>
</table>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post, html: {class: "form-horizontal", role: "form"} do %>
    <fieldset>
      <legend>Innlogging</legend>
      <br/>

      <div class="form-group">
        <%= label_tag :username, "Brukernavn:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">
          <%= text_field_tag :username %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag :password, "Passord: ", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">
          <%= password_field_tag :password %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10 controls">
          <%= submit_tag(value="Logg inn", {class: "btn btn-default"}) %>
        </div>
      </div>
    </fieldset>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

app/views/users/edit.html.erb
<% if current_user && current_user.id == @user.id || current_user && current_user.is_admin? %>
<%= form_for(@user, html: {class: "form-horizontal", role: "form"}) do |f| %>
    <fieldset>
      <legend>Rediger opplysninger for <%= @user.name %></legend>
      <br />
      <div class="form-group">
        <%= f.label :name, "Navn:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">
          <%= f.text_field :name, {class: "form-control"} %>
        </div>
      </div>

      <div class="form-group">

        <%= f.label :username, "Brukernavn:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">

          <%= f.text_field :username %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "Passord:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">

          <%= f.text_field :password %>
        </div>
      </div>


      <% if current_user && current_user.is_admin? %>
      <div class="form-group">

        <div class="col-lg-offset-2 col-lg-10 controls">
          <div class="checkbox">
            <label for="user_admin">
              <%= f.check_box :admin %> Adminbruker
            </label>

          </div>
        </div>
      </div>
      <% end %>

      <div class="form-group">

        <%= f.label :phone, "Telefon:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">

          <%= f.text_field :phone %>
        </div>
      </div>

      <div class="form-group">

        <%= f.label :email, "Epost:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">

          <%= f.text_field :email %>
        </div>
      </div>

      <div class="form-group">

        <div class="col-lg-offset-2 col-lg-10 controls">
          <div class="checkbox">
            <label for="user_active"><%= f.check_box :active %>Aktiv
            </label>
          </div>
        </div>
      </div>

      <div class="form-group">

        <%= f.label :comments, "Kommentarer:", {class: "col-lg-2 control-label"} %>
        <div class="col-lg-10 controls">

          <%= f.text_area :comments %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10 controls">
          <%= f.submit(value="Lagre", {class:"btn btn-default"}) %>
        </div>
      </div>

    </fieldset>
<% end %>
<% end %>

app/views/users/index.html.erb
<h1>Vaktliste</h1>
<ul>

  <% @users.each do |user| %>
    <li><%= link_to(user.name, vakt_path(user)) %></li>
  <% end  %>

</ul>

<p><%= link_to("Registrer ny person", ny_vakt_path) %></p>

app/views/users/new.html.erb
<%= form_for(@user, url: opprett_vakt_path, html: {class: "form-horizontal", role: "form"}) do |f| %>
    <fieldset>
      <legend>Registrer ny bruker</legend>
      <br />
      <% if current_user && current_user.is_admin? %>
    <div class="form-group">
      <%= f.label :name, "Navn:", {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10 controls">
        <%= f.text_field :name, {class: "form-control"} %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :username, "Brukernavn:", {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10 controls">

        <%= f.text_field :username %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, "Passord:", {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10 controls">

        <%= f.text_field :password %>
      </div>
    </div>


    <div class="form-group">

      <div class="col-lg-offset-2 col-lg-10 controls">
        <div class="checkbox">
          <label for="user_admin">
            <%= f.check_box :admin %> Adminbruker
          </label>

        </div>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :phone, "Telefon:", {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10 controls">

        <%= f.text_field :phone %>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :email, "Epost:", {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10 controls">

        <%= f.text_field :email %>
      </div>
    </div>

    <div class="form-group">

      <div class="col-lg-offset-2 col-lg-10 controls">
        <div class="checkbox">
          <label for="user_active"><%= f.check_box :active %>Aktiv
          </label>
        </div>
      </div>
    </div>

    <div class="form-group">

      <%= f.label :comments, "Kommentarer:", {class: "col-lg-2 control-label"} %>
      <div class="col-lg-10 controls">

        <%= f.text_area :comments %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10 controls">
        <%= f.submit(value="Lagre", {class:"btn btn-default"}) %>
      </div>
    </div>
      <%else%>
       <p>Bare brukere med administrator-rettigheter kan registrere nye brukere.</p>
      <% end %>

</fieldset>
<% end %>

app/views/users/show.html.erb
<article>
  <header>
    <h1><%= @user.name %></h1>
  </header>

<% if (current_user && current_user.id == @user.id) || (current_user && current_user.is_admin?) %>
<p><%= link_to("Rediger opplysninger", rediger_vakt_path(@user)) %></p>
<% end %>
<ul>
  <li>Telefon: <%=  @user.phone  %></li>
  <li>Epost: <%= @user.email  %></li>
  <li>Brukernavn: <%=  @user.username  %></li>
  <li>Passord: <%= @user.password  %></li>
  <li>Admin: <%= @user.admin == true ? "Ja" : "Nei"  %></li>
  <li>Sist oppdatert: <%= @user.updated_at  %></li>
</ul>

<p>
Merknader: <%= @user.comments %>
</p>

<h3>Oppsatte vakter</h3>
<ul>
  <% @workdays.each do |w| %>
     <li> <%= I18n.localize w.date, :format => :long  %> </li>
  <% end %>
</ul>

</article>

app/views/workdays/update.js.erb
$("#person_1_day_<%=@day.id%>").html("Vakt 1: <%= @day.person_1.nil? ? "ingen" : @day.person_1.name %>")
$("#person_2_day_<%=@day.id%>").html("Vakt 2: <%= @day.person_2.nil? ? "ingen" : @day.person_2.name %>")
$("#info_day_<%=@day.id%>").attr("class", "<%= @day.status_level %>")